/******************** (C) COPYRIGHT  XI`AN QEXPAND *******************************
* 文件名  ：DrvDi.c
* 描述    ：Di驱动文件       
* 实验平台：ECU
* 库版本  ：V1.0.0
* 作者    ：
* 修改时间: 2023-05-16
**********************************************************************************/	
#include "Device.h"
	
void vDrvDiInit(void)
{
#if (CTLBOARD_TYPE == _HB4_GD32)
	/*******************************************************************************
	* DI	
	*管脚3	 PE4		B-SWI1_R; 	 *管脚4		PE5		B-SWI2_R; 

	*管脚5	 PE6		B-SWI3_R; 	 *管脚8		PC14	B-SWI4_R; 

	*管脚7	 PC13		B-SWI5_R;    *管脚9		PC15	B-SWI6_R;

	*管脚39	 PE8		B-SWI7_R;    *管脚46 	PE15	B-SWI8_R;

	*管脚97	 PE0		DRIVER1_R; 	 *管脚98 	PE1		DRIVER2_R;

	*管脚95	 PB8		DRIVER3_R;	 *管脚96 	PB9		DRIVER4_R;

	*管脚90	 PB4		DRIVER5_R;	 *管脚67	PA8		DRIVER6_R;	

	*管脚68	PA9			DRIVER7_R;	 *管脚69	PA10	DRIVER8_R;	

	*管脚82	 PD1		DRIVER9_R;	 *管脚83	PD2		DRIVER10_R;

	*管脚84	 PD3		DRIVER11_R;	 *管脚85	PD4		DRIVER12_R;

	*******************************************************************************/
	gpio_init(SWI1_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI1_Pin);
    gpio_init(SWI2_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI2_Pin);
    gpio_init(SWI3_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI3_Pin);
    gpio_init(SWI4_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI4_Pin);
    gpio_init(SWI5_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI5_Pin);
    gpio_init(SWI6_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI6_Pin);
    gpio_init(SWI7_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI7_Pin);
    gpio_init(SWI8_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI8_Pin);
    gpio_init(DRIVER1_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER1_R_Pin);
    gpio_init(DRIVER2_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER2_R_Pin);
    gpio_init(DRIVER3_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER3_R_Pin);
    gpio_init(DRIVER4_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER4_R_Pin);
    gpio_init(DRIVER5_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER5_R_Pin);
    gpio_init(DRIVER6_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER6_R_Pin);
    gpio_init(DRIVER7_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER7_R_Pin);
    gpio_init(DRIVER8_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER8_R_Pin);
    gpio_init(DRIVER9_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER9_R_Pin);
    gpio_init(DRIVER10_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER10_R_Pin);
    gpio_init(DRIVER11_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER11_R_Pin);
    gpio_init(DRIVER12_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER12_R_Pin);
	
	gpio_init(WATCH_DOG_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, WATCH_DOG_R_Pin);
#endif //#if (CTLBOARD_TYPE == _HB4_GD32)

#if (CTLBOARD_TYPE == _HB6_GD32)
	/*******************************************************************************
	* DI	
	*管脚3	 PE4		B-SWI1_R; 	 *管脚4		PE5		B-SWI2_R; 

	*管脚5	 PE6		B-SWI3_R; 	 *管脚7		PC13	B-SWI4_R; 

	*管脚8	 PC14		B-SWI5_R;    *管脚9		PC15	B-SWI6_R;

	*管脚38	 PE7		B-SWI7_R;    *管脚39 	PE8		B-SWI8_R;
	
	*管脚17	 PC2		B-SWI9_R;    *管脚18	PC3		B-SWI10_R;

	*管脚44	 PE13		B-SWI11_R;   *管脚45 	PE14	B-SWI12_R;

	*管脚98	 PE1		DRIVER1_R; 	 *管脚97 	PE0		DRIVER2_R;

	*管脚95	 PB8		DRIVER3_R;	 *管脚82 	PD1		DRIVER4_R;

	*管脚69	 PA10		DRIVER5_R;	 *管脚90	PB4		DRIVER6_R;	

	*管脚67	 PA8		DRIVER7_R;	 *管脚96	PAB9	DRIVER8_R;	

	*管脚85	 PD4		DRIVER9_R;	 *管脚68	PA9		DRIVER10_R;

	*管脚84	 PD3		DRIVER11_R;	 *管脚83	PD2		DRIVER12_R;

	*******************************************************************************/
	gpio_init(SWI1_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI1_Pin);
    gpio_init(SWI2_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI2_Pin);
    gpio_init(SWI3_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI3_Pin);
    gpio_init(SWI4_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI4_Pin);
    gpio_init(SWI5_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI5_Pin);
    gpio_init(SWI6_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI6_Pin);
    gpio_init(SWI7_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI7_Pin);
    gpio_init(SWI8_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI8_Pin);
    gpio_init(SWI9_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI9_Pin);
    gpio_init(SWI10_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI10_Pin);
    gpio_init(SWI11_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI11_Pin);
    gpio_init(SWI12_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, SWI12_Pin);
	
    gpio_init(DRIVER1_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER1_R_Pin);
    gpio_init(DRIVER2_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER2_R_Pin);
    gpio_init(DRIVER3_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER3_R_Pin);
    gpio_init(DRIVER4_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER4_R_Pin);
    gpio_init(DRIVER5_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER5_R_Pin);
    gpio_init(DRIVER6_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER6_R_Pin);
    gpio_init(DRIVER7_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER7_R_Pin);
    gpio_init(DRIVER8_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER8_R_Pin);
    gpio_init(DRIVER9_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER9_R_Pin);
    gpio_init(DRIVER10_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER10_R_Pin);
    gpio_init(DRIVER11_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER11_R_Pin);
    gpio_init(DRIVER12_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, DRIVER12_R_Pin);
	
	gpio_init(WATCH_DOG_R_GPIO_Port, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, WATCH_DOG_R_Pin);
#endif //#if (CTLBOARD_TYPE == _HB6_GD32)

}

